name: Rust

on:
  push:
    branches: [ feature/github-actions-ci-cd ]
    paths:
    - 'libindy/**'

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Build Env
      run: sudo apt-get install -y build-essential pkg-config cmake libssl-dev libsqlite3-dev libzmq3-dev libncursesw5-dev libsodium-dev
    - name: Build
      run: cargo build --verbose
      working-directory: ./libindy
    - name: Compress 
      run: zip libindy.zip libindy.so
      working-directory: ./libindy/target/debug
    - name: Upload
      env: 
        NEXUX_ID: ${{secrets.NexusId}}
        NEXUS_PW: ${{secrets.NexusPass}}
      run: curl -v --user '"$NEXUS_ID":"$NEXUS_PW"' --upload-file libindy.zip http://13.125.219.189/repository/libraries/linux/libindy.zip
      working-directory: ./libindy/target/debug
